import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css'
import Header from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Header />
          <div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
